spring:
  cloud:
    schema-registry-client:
      endpoint: http://${SCHEMA_REGISTRY_HOST:localhost}:${SCHEMA_REGISTRY_PORT:8081}
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
          min-partition-count: 2
      bindings:
        news-in-0:
          destination: com.mycompany.newspipeline.categorizer.news
          content-type: application/*+avro
          group: collectorGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        news-out-0:
          destination: com.mycompany.newspipeline.collector.news
          content-type: application/*+avro
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
        news-in-1:
          destination: com.mycompany.bayitepipeline.categorizer.bayite
          content-type: application/*+avro
          group: collectorGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        news-out-1:
          destination: com.mycompany.bayitepipeline.collector.bayite
          content-type: application/*+avro
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 3
        news-in-2:
          destination: com.mycompany.khassidapipeline.categorizer.khassida
          content-type: application/*+avro
          group: collectorGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        news-out-2:
          destination: com.mycompany.khassidapipeline.collector.khassida
          content-type: application/*+avro
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 3

  data:
    elasticsearch:
      cluster-name: docker-es-cluster
      cluster-nodes: ${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_NODES_PORT:9300}
  elasticsearch:
    rest:
      uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_REST_PORT:9200}
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true
