/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mycompany.commonsbayite.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BayiteEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1315341955027325431L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BayiteEvent\",\"namespace\":\"com.mycompany.commonsbayite.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":\"string\"},{\"name\":\"bayitear\",\"type\":\"string\"},{\"name\":\"bayitefr\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bayiteen\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bayiteit\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bayitees\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bayitewo\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bayitept\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bayitech\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"khassida\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BayiteEvent> ENCODER =
      new BinaryMessageEncoder<BayiteEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BayiteEvent> DECODER =
      new BinaryMessageDecoder<BayiteEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BayiteEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BayiteEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BayiteEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BayiteEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BayiteEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BayiteEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BayiteEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BayiteEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence numero;
   private java.lang.CharSequence bayitear;
   private java.lang.CharSequence bayitefr;
   private java.lang.CharSequence bayiteen;
   private java.lang.CharSequence bayiteit;
   private java.lang.CharSequence bayitees;
   private java.lang.CharSequence bayitewo;
   private java.lang.CharSequence bayitept;
   private java.lang.CharSequence bayitech;
   private java.lang.CharSequence khassida;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BayiteEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param numero The new value for numero
   * @param bayitear The new value for bayitear
   * @param bayitefr The new value for bayitefr
   * @param bayiteen The new value for bayiteen
   * @param bayiteit The new value for bayiteit
   * @param bayitees The new value for bayitees
   * @param bayitewo The new value for bayitewo
   * @param bayitept The new value for bayitept
   * @param bayitech The new value for bayitech
   * @param khassida The new value for khassida
   */
  public BayiteEvent(java.lang.CharSequence id, java.lang.CharSequence numero, java.lang.CharSequence bayitear, java.lang.CharSequence bayitefr, java.lang.CharSequence bayiteen, java.lang.CharSequence bayiteit, java.lang.CharSequence bayitees, java.lang.CharSequence bayitewo, java.lang.CharSequence bayitept, java.lang.CharSequence bayitech, java.lang.CharSequence khassida) {
    this.id = id;
    this.numero = numero;
    this.bayitear = bayitear;
    this.bayitefr = bayitefr;
    this.bayiteen = bayiteen;
    this.bayiteit = bayiteit;
    this.bayitees = bayitees;
    this.bayitewo = bayitewo;
    this.bayitept = bayitept;
    this.bayitech = bayitech;
    this.khassida = khassida;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return numero;
    case 2: return bayitear;
    case 3: return bayitefr;
    case 4: return bayiteen;
    case 5: return bayiteit;
    case 6: return bayitees;
    case 7: return bayitewo;
    case 8: return bayitept;
    case 9: return bayitech;
    case 10: return khassida;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: numero = (java.lang.CharSequence)value$; break;
    case 2: bayitear = (java.lang.CharSequence)value$; break;
    case 3: bayitefr = (java.lang.CharSequence)value$; break;
    case 4: bayiteen = (java.lang.CharSequence)value$; break;
    case 5: bayiteit = (java.lang.CharSequence)value$; break;
    case 6: bayitees = (java.lang.CharSequence)value$; break;
    case 7: bayitewo = (java.lang.CharSequence)value$; break;
    case 8: bayitept = (java.lang.CharSequence)value$; break;
    case 9: bayitech = (java.lang.CharSequence)value$; break;
    case 10: khassida = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'numero' field.
   * @return The value of the 'numero' field.
   */
  public java.lang.CharSequence getNumero() {
    return numero;
  }


  /**
   * Sets the value of the 'numero' field.
   * @param value the value to set.
   */
  public void setNumero(java.lang.CharSequence value) {
    this.numero = value;
  }

  /**
   * Gets the value of the 'bayitear' field.
   * @return The value of the 'bayitear' field.
   */
  public java.lang.CharSequence getBayitear() {
    return bayitear;
  }


  /**
   * Sets the value of the 'bayitear' field.
   * @param value the value to set.
   */
  public void setBayitear(java.lang.CharSequence value) {
    this.bayitear = value;
  }

  /**
   * Gets the value of the 'bayitefr' field.
   * @return The value of the 'bayitefr' field.
   */
  public java.lang.CharSequence getBayitefr() {
    return bayitefr;
  }


  /**
   * Sets the value of the 'bayitefr' field.
   * @param value the value to set.
   */
  public void setBayitefr(java.lang.CharSequence value) {
    this.bayitefr = value;
  }

  /**
   * Gets the value of the 'bayiteen' field.
   * @return The value of the 'bayiteen' field.
   */
  public java.lang.CharSequence getBayiteen() {
    return bayiteen;
  }


  /**
   * Sets the value of the 'bayiteen' field.
   * @param value the value to set.
   */
  public void setBayiteen(java.lang.CharSequence value) {
    this.bayiteen = value;
  }

  /**
   * Gets the value of the 'bayiteit' field.
   * @return The value of the 'bayiteit' field.
   */
  public java.lang.CharSequence getBayiteit() {
    return bayiteit;
  }


  /**
   * Sets the value of the 'bayiteit' field.
   * @param value the value to set.
   */
  public void setBayiteit(java.lang.CharSequence value) {
    this.bayiteit = value;
  }

  /**
   * Gets the value of the 'bayitees' field.
   * @return The value of the 'bayitees' field.
   */
  public java.lang.CharSequence getBayitees() {
    return bayitees;
  }


  /**
   * Sets the value of the 'bayitees' field.
   * @param value the value to set.
   */
  public void setBayitees(java.lang.CharSequence value) {
    this.bayitees = value;
  }

  /**
   * Gets the value of the 'bayitewo' field.
   * @return The value of the 'bayitewo' field.
   */
  public java.lang.CharSequence getBayitewo() {
    return bayitewo;
  }


  /**
   * Sets the value of the 'bayitewo' field.
   * @param value the value to set.
   */
  public void setBayitewo(java.lang.CharSequence value) {
    this.bayitewo = value;
  }

  /**
   * Gets the value of the 'bayitept' field.
   * @return The value of the 'bayitept' field.
   */
  public java.lang.CharSequence getBayitept() {
    return bayitept;
  }


  /**
   * Sets the value of the 'bayitept' field.
   * @param value the value to set.
   */
  public void setBayitept(java.lang.CharSequence value) {
    this.bayitept = value;
  }

  /**
   * Gets the value of the 'bayitech' field.
   * @return The value of the 'bayitech' field.
   */
  public java.lang.CharSequence getBayitech() {
    return bayitech;
  }


  /**
   * Sets the value of the 'bayitech' field.
   * @param value the value to set.
   */
  public void setBayitech(java.lang.CharSequence value) {
    this.bayitech = value;
  }

  /**
   * Gets the value of the 'khassida' field.
   * @return The value of the 'khassida' field.
   */
  public java.lang.CharSequence getKhassida() {
    return khassida;
  }


  /**
   * Sets the value of the 'khassida' field.
   * @param value the value to set.
   */
  public void setKhassida(java.lang.CharSequence value) {
    this.khassida = value;
  }

  /**
   * Creates a new BayiteEvent RecordBuilder.
   * @return A new BayiteEvent RecordBuilder
   */
  public static com.mycompany.commonsbayite.avro.BayiteEvent.Builder newBuilder() {
    return new com.mycompany.commonsbayite.avro.BayiteEvent.Builder();
  }

  /**
   * Creates a new BayiteEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BayiteEvent RecordBuilder
   */
  public static com.mycompany.commonsbayite.avro.BayiteEvent.Builder newBuilder(com.mycompany.commonsbayite.avro.BayiteEvent.Builder other) {
    if (other == null) {
      return new com.mycompany.commonsbayite.avro.BayiteEvent.Builder();
    } else {
      return new com.mycompany.commonsbayite.avro.BayiteEvent.Builder(other);
    }
  }

  /**
   * Creates a new BayiteEvent RecordBuilder by copying an existing BayiteEvent instance.
   * @param other The existing instance to copy.
   * @return A new BayiteEvent RecordBuilder
   */
  public static com.mycompany.commonsbayite.avro.BayiteEvent.Builder newBuilder(com.mycompany.commonsbayite.avro.BayiteEvent other) {
    if (other == null) {
      return new com.mycompany.commonsbayite.avro.BayiteEvent.Builder();
    } else {
      return new com.mycompany.commonsbayite.avro.BayiteEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BayiteEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BayiteEvent>
    implements org.apache.avro.data.RecordBuilder<BayiteEvent> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence numero;
    private java.lang.CharSequence bayitear;
    private java.lang.CharSequence bayitefr;
    private java.lang.CharSequence bayiteen;
    private java.lang.CharSequence bayiteit;
    private java.lang.CharSequence bayitees;
    private java.lang.CharSequence bayitewo;
    private java.lang.CharSequence bayitept;
    private java.lang.CharSequence bayitech;
    private java.lang.CharSequence khassida;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mycompany.commonsbayite.avro.BayiteEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.numero)) {
        this.numero = data().deepCopy(fields()[1].schema(), other.numero);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.bayitear)) {
        this.bayitear = data().deepCopy(fields()[2].schema(), other.bayitear);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.bayitefr)) {
        this.bayitefr = data().deepCopy(fields()[3].schema(), other.bayitefr);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.bayiteen)) {
        this.bayiteen = data().deepCopy(fields()[4].schema(), other.bayiteen);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.bayiteit)) {
        this.bayiteit = data().deepCopy(fields()[5].schema(), other.bayiteit);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.bayitees)) {
        this.bayitees = data().deepCopy(fields()[6].schema(), other.bayitees);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.bayitewo)) {
        this.bayitewo = data().deepCopy(fields()[7].schema(), other.bayitewo);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.bayitept)) {
        this.bayitept = data().deepCopy(fields()[8].schema(), other.bayitept);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.bayitech)) {
        this.bayitech = data().deepCopy(fields()[9].schema(), other.bayitech);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.khassida)) {
        this.khassida = data().deepCopy(fields()[10].schema(), other.khassida);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing BayiteEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mycompany.commonsbayite.avro.BayiteEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numero)) {
        this.numero = data().deepCopy(fields()[1].schema(), other.numero);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bayitear)) {
        this.bayitear = data().deepCopy(fields()[2].schema(), other.bayitear);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.bayitefr)) {
        this.bayitefr = data().deepCopy(fields()[3].schema(), other.bayitefr);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.bayiteen)) {
        this.bayiteen = data().deepCopy(fields()[4].schema(), other.bayiteen);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.bayiteit)) {
        this.bayiteit = data().deepCopy(fields()[5].schema(), other.bayiteit);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bayitees)) {
        this.bayitees = data().deepCopy(fields()[6].schema(), other.bayitees);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bayitewo)) {
        this.bayitewo = data().deepCopy(fields()[7].schema(), other.bayitewo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.bayitept)) {
        this.bayitept = data().deepCopy(fields()[8].schema(), other.bayitept);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.bayitech)) {
        this.bayitech = data().deepCopy(fields()[9].schema(), other.bayitech);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.khassida)) {
        this.khassida = data().deepCopy(fields()[10].schema(), other.khassida);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumero() {
      return numero;
    }


    /**
      * Sets the value of the 'numero' field.
      * @param value The value of 'numero'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setNumero(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.numero = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'numero' field has been set.
      * @return True if the 'numero' field has been set, false otherwise.
      */
    public boolean hasNumero() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'numero' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearNumero() {
      numero = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayitear' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayitear() {
      return bayitear;
    }


    /**
      * Sets the value of the 'bayitear' field.
      * @param value The value of 'bayitear'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayitear(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bayitear = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bayitear' field has been set.
      * @return True if the 'bayitear' field has been set, false otherwise.
      */
    public boolean hasBayitear() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bayitear' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayitear() {
      bayitear = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayitefr' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayitefr() {
      return bayitefr;
    }


    /**
      * Sets the value of the 'bayitefr' field.
      * @param value The value of 'bayitefr'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayitefr(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.bayitefr = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'bayitefr' field has been set.
      * @return True if the 'bayitefr' field has been set, false otherwise.
      */
    public boolean hasBayitefr() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'bayitefr' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayitefr() {
      bayitefr = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayiteen' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayiteen() {
      return bayiteen;
    }


    /**
      * Sets the value of the 'bayiteen' field.
      * @param value The value of 'bayiteen'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayiteen(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.bayiteen = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'bayiteen' field has been set.
      * @return True if the 'bayiteen' field has been set, false otherwise.
      */
    public boolean hasBayiteen() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'bayiteen' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayiteen() {
      bayiteen = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayiteit' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayiteit() {
      return bayiteit;
    }


    /**
      * Sets the value of the 'bayiteit' field.
      * @param value The value of 'bayiteit'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayiteit(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.bayiteit = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'bayiteit' field has been set.
      * @return True if the 'bayiteit' field has been set, false otherwise.
      */
    public boolean hasBayiteit() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'bayiteit' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayiteit() {
      bayiteit = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayitees' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayitees() {
      return bayitees;
    }


    /**
      * Sets the value of the 'bayitees' field.
      * @param value The value of 'bayitees'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayitees(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.bayitees = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'bayitees' field has been set.
      * @return True if the 'bayitees' field has been set, false otherwise.
      */
    public boolean hasBayitees() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'bayitees' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayitees() {
      bayitees = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayitewo' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayitewo() {
      return bayitewo;
    }


    /**
      * Sets the value of the 'bayitewo' field.
      * @param value The value of 'bayitewo'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayitewo(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.bayitewo = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'bayitewo' field has been set.
      * @return True if the 'bayitewo' field has been set, false otherwise.
      */
    public boolean hasBayitewo() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'bayitewo' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayitewo() {
      bayitewo = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayitept' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayitept() {
      return bayitept;
    }


    /**
      * Sets the value of the 'bayitept' field.
      * @param value The value of 'bayitept'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayitept(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.bayitept = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'bayitept' field has been set.
      * @return True if the 'bayitept' field has been set, false otherwise.
      */
    public boolean hasBayitept() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'bayitept' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayitept() {
      bayitept = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'bayitech' field.
      * @return The value.
      */
    public java.lang.CharSequence getBayitech() {
      return bayitech;
    }


    /**
      * Sets the value of the 'bayitech' field.
      * @param value The value of 'bayitech'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setBayitech(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.bayitech = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'bayitech' field has been set.
      * @return True if the 'bayitech' field has been set, false otherwise.
      */
    public boolean hasBayitech() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'bayitech' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearBayitech() {
      bayitech = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'khassida' field.
      * @return The value.
      */
    public java.lang.CharSequence getKhassida() {
      return khassida;
    }


    /**
      * Sets the value of the 'khassida' field.
      * @param value The value of 'khassida'.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder setKhassida(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.khassida = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'khassida' field has been set.
      * @return True if the 'khassida' field has been set, false otherwise.
      */
    public boolean hasKhassida() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'khassida' field.
      * @return This builder.
      */
    public com.mycompany.commonsbayite.avro.BayiteEvent.Builder clearKhassida() {
      khassida = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BayiteEvent build() {
      try {
        BayiteEvent record = new BayiteEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.numero = fieldSetFlags()[1] ? this.numero : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bayitear = fieldSetFlags()[2] ? this.bayitear : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.bayitefr = fieldSetFlags()[3] ? this.bayitefr : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.bayiteen = fieldSetFlags()[4] ? this.bayiteen : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.bayiteit = fieldSetFlags()[5] ? this.bayiteit : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.bayitees = fieldSetFlags()[6] ? this.bayitees : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.bayitewo = fieldSetFlags()[7] ? this.bayitewo : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.bayitept = fieldSetFlags()[8] ? this.bayitept : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.bayitech = fieldSetFlags()[9] ? this.bayitech : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.khassida = fieldSetFlags()[10] ? this.khassida : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BayiteEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BayiteEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BayiteEvent>
    READER$ = (org.apache.avro.io.DatumReader<BayiteEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.numero);

    out.writeString(this.bayitear);

    if (this.bayitefr == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayitefr);
    }

    if (this.bayiteen == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayiteen);
    }

    if (this.bayiteit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayiteit);
    }

    if (this.bayitees == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayitees);
    }

    if (this.bayitewo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayitewo);
    }

    if (this.bayitept == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayitept);
    }

    if (this.bayitech == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bayitech);
    }

    if (this.khassida == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.khassida);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.numero = in.readString(this.numero instanceof Utf8 ? (Utf8)this.numero : null);

      this.bayitear = in.readString(this.bayitear instanceof Utf8 ? (Utf8)this.bayitear : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayitefr = null;
      } else {
        this.bayitefr = in.readString(this.bayitefr instanceof Utf8 ? (Utf8)this.bayitefr : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayiteen = null;
      } else {
        this.bayiteen = in.readString(this.bayiteen instanceof Utf8 ? (Utf8)this.bayiteen : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayiteit = null;
      } else {
        this.bayiteit = in.readString(this.bayiteit instanceof Utf8 ? (Utf8)this.bayiteit : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayitees = null;
      } else {
        this.bayitees = in.readString(this.bayitees instanceof Utf8 ? (Utf8)this.bayitees : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayitewo = null;
      } else {
        this.bayitewo = in.readString(this.bayitewo instanceof Utf8 ? (Utf8)this.bayitewo : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayitept = null;
      } else {
        this.bayitept = in.readString(this.bayitept instanceof Utf8 ? (Utf8)this.bayitept : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bayitech = null;
      } else {
        this.bayitech = in.readString(this.bayitech instanceof Utf8 ? (Utf8)this.bayitech : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.khassida = null;
      } else {
        this.khassida = in.readString(this.khassida instanceof Utf8 ? (Utf8)this.khassida : null);
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.numero = in.readString(this.numero instanceof Utf8 ? (Utf8)this.numero : null);
          break;

        case 2:
          this.bayitear = in.readString(this.bayitear instanceof Utf8 ? (Utf8)this.bayitear : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayitefr = null;
          } else {
            this.bayitefr = in.readString(this.bayitefr instanceof Utf8 ? (Utf8)this.bayitefr : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayiteen = null;
          } else {
            this.bayiteen = in.readString(this.bayiteen instanceof Utf8 ? (Utf8)this.bayiteen : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayiteit = null;
          } else {
            this.bayiteit = in.readString(this.bayiteit instanceof Utf8 ? (Utf8)this.bayiteit : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayitees = null;
          } else {
            this.bayitees = in.readString(this.bayitees instanceof Utf8 ? (Utf8)this.bayitees : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayitewo = null;
          } else {
            this.bayitewo = in.readString(this.bayitewo instanceof Utf8 ? (Utf8)this.bayitewo : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayitept = null;
          } else {
            this.bayitept = in.readString(this.bayitept instanceof Utf8 ? (Utf8)this.bayitept : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bayitech = null;
          } else {
            this.bayitech = in.readString(this.bayitech instanceof Utf8 ? (Utf8)this.bayitech : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.khassida = null;
          } else {
            this.khassida = in.readString(this.khassida instanceof Utf8 ? (Utf8)this.khassida : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










